services:
  postgres:
    image: postgres:latest
    container_name: microservice-postgres
    environment:
      POSTGRES_PASSWORD: Password1!
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
